name: Deploy to GitHub Pages
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Build site
        run: |
          bundle install --binstubs
          JEKYLL_ENV=production ./bin/jekyll build

      - name: Deploy to gh-pages
        run: |
          cd _site
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "GitHub Actions: Publishing Static site - $(date)"
          git push --force "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" gh-pages:gh-pages
